// Generated by view binder compiler. Do not edit!
package com.example.floresapp.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.floresapp.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivitySplashscreenBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final ImageView TituloBienvenido;

  @NonNull
  public final TextView textViewNombreApp;

  @NonNull
  public final TextView textViewSaludo;

  private ActivitySplashscreenBinding(@NonNull ConstraintLayout rootView,
      @NonNull ImageView TituloBienvenido, @NonNull TextView textViewNombreApp,
      @NonNull TextView textViewSaludo) {
    this.rootView = rootView;
    this.TituloBienvenido = TituloBienvenido;
    this.textViewNombreApp = textViewNombreApp;
    this.textViewSaludo = textViewSaludo;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivitySplashscreenBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivitySplashscreenBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_splashscreen, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivitySplashscreenBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.TituloBienvenido;
      ImageView TituloBienvenido = ViewBindin